### ISSUE TITLE
根原型对象的原型是 undefined？

### ISSUE THREAD

**Issue by sushoucanyuan** [lcx960324/fe-interview-cheat-sheet#2]
通过 Object.getPrototypeOf(Object.prototype) 得到的是 null

**Comment by umarufans** [comment]
返回 null 并不是因为根原型对象的原型是 null ：
![image](https://user-images.githubusercontent.com/9768245/30773493-1c0ca14e-a0a4-11e7-8a8f-2505e4561aa7.png)
不过确实表述不合理，`Object.prototype.__proto__` 的确是 `null`，这个是用来表示该原型对象没有原型的。
感谢反馈~

**Comment by umarufans** [comment]
已更新：https://github.com/lcx960324/fe-interview-cheat-sheet/commit/a6bd852c9454108b8102f2c25dacd1c315229227
XD
