### ISSUE TITLE
HTML & CSS 篇中关于 px 的错误

### ISSUE THREAD

**Issue by youngBrain1893** [lcx960324/fe-interview-cheat-sheet#4]
1. `px` 是相对单位而不是绝对单位
相应的 `in` 和 `cm` 到 `px` 的转化也是错误的

2. `pt` 和 `pc` 是绝对单位，`1 in = 72pt`, `1pc = 12pt`

**Comment by umarufans** [comment]
我觉得说 `px` 是相对单位也不妥。我认为他确实是一个绝对单位，只不过受浏览器行为的影响罢了。

下边的换算确实不妥，这个地方我会做修改，谢谢 ~
